spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestionstock
    username: root
    password:
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        ejb:
          interceptor: com.fadel.gestiondestock.interceptor.Interceptor
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8082
flickr:
  apiKey: 53b40d03600df6d09e2eb4684312ceda
  apiSecret: 6bccfbe0befe66f4
  appKey: 72157720866174225-0ff35af7cc357414
  appSecret: e155efe20f9d1adc


